  language: python
  python:
    - 3.6
    - nightly
  script:
    - python -m unittest discover
    - codecov
  install:
    - pip install python-levenshtein  # e.g. see https://github.com/pallets/jinja/blob/master/.travis.yml
