language: python
python:
  - 3.6
  - nightly
script:
  - python -m unittest discover
  - coverage run -m unittest discover
install:
  - pip install python-levenshtein  # e.g. see https://github.com/pallets/jinja/blob/master/.travis.yml
  - pip install codecov
  - pip install coverage
after_success:
  - codecov