language: python
python:
  - 3.6
  - nightly
script:
  - python -m unittest discover
  - coverage run -m unittest discover
  - pylint fuzzymatcher/
install:
  - pip install pandas  # e.g. see https://github.com/pallets/jinja/blob/master/.travis.yml
  - pip install codecov
  - pip install coverage
  - pip install pylint
after_success:
  - codecov